// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wasyffceigndovssyjis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indhc3lmZmNlaWduZG92c3N5amlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMjcyNTUsImV4cCI6MjA3MjgwMzI1NX0.sW6vBRd3zwFXjqi6QUG7aA-5EwangEdc1_ncei9tt2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});